### ISSUE TITLE
Duplicate key "FAILED_DEPENDENCY" in object literal [duplicate-object-key]

### ISSUE THREAD

**Issue by TimKieu** [OultimoCoder/cloudflare-planetscale-hono-boilerplate#23]
▲ [WARNING] Duplicate key "FAILED_DEPENDENCY" in object literal [duplicate-object-key]

    dist/index.mjs:20:26288:
      20 │ ... might be replayed.","425_CLASS":I.CLIENT_ERROR,FAILED_DEPENDENCY:425,426:"Upgrade Required","426_NAME":"UPGRADE_...
         ╵                                                    ~~~~~~~~~~~~~~~~~

  The original key "FAILED_DEPENDENCY" is here:

    dist/index.mjs:20:26107:
      20 │ ...hat request failed.","424_CLASS":I.CLIENT_ERROR,FAILED_DEPENDENCY:424,425:"Too Early","425_NAME":"TOO_EARLY","425...
         ╵                                                    ~~~~~~~~~~~~~~~~~

I got this issue and finding the way to fix.

**Comment by OultimoCoder** [comment]
Can you give me some more details on how you encountered this? I use this repo a lot and have never seen this.

**Comment by TimKieu** [comment]
yes, please kindly take a look I try again in this platform:
macos m1/m2 13.6/14.0
node 18.18
git clone https://github.com/OultimoCoder/cloudflare-planetscale-hono-boilerplate
cd cloudflare-planetscale-hono-boilerplate
pnpm i && pnpm build
pnpm dev

Here is the output console:
> create-cf-planetscale-app@1.2.2 dev /Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate
> wrangler dev dist/index.mjs --live-reload --log-level debug --port 8787

 ⛅️ wrangler 3.10.0
-------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
▲ [WARNING] Duplicate key "FAILED_DEPENDENCY" in object literal [duplicate-object-key]

    dist/index.mjs:20:26288:
      20 │ ...ed.","425_CLASS":I.CLIENT_ERROR,FAILED_DEPENDENCY:425,426:"Upgrade Required","42...
         ╵                                    ~~~~~~~~~~~~~~~~~

  The original key "FAILED_DEPENDENCY" is here:

    dist/index.mjs:20:26107:
      20 │ ...ed.","424_CLASS":I.CLIENT_ERROR,FAILED_DEPENDENCY:424,425:"Too Early","425_NAME"...
         ╵                                    ~~~~~~~~~~~~~~~~~

Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":false}}.
Failed to load .env file "/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/.dev.vars": Error: ENOENT: no such file or directory, open '/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/.dev.vars'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at tryLoadDotEnv (/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:124088:72)
    at loadDotEnv (/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:124097:12)
    at getVarsForDev (/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:151236:18)
    at getBindings (/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:152146:10)
    at getBindingsAndAssetPaths (/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:152104:20)
    at getDevReactElement (/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:151787:40)
    at startDev (/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/node_modules/.pnpm/wrangler@3.10.0/node_modules/wrangler/wrangler-dist/cli.js:151848:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/tim/2dev/github/timkieu/cloudflare-planetscale-hono-boilerplate/.dev.vars'
}
▲ [WARNING] Duplicate key "FAILED_DEPENDENCY" in object literal [duplicate-object-key]

    dist/index.mjs:20:26288:
      20 │ ..._CLASS":I.CLIENT_ERROR,FAILED_DEPENDENCY:425,426:"Upgrade Requi...
         ╵                           ~~~~~~~~~~~~~~~~~

  The original key "FAILED_DEPENDENCY" is here:

    dist/index.mjs:20:26107:
      20 │ ..._CLASS":I.CLIENT_ERROR,FAILED_DEPENDENCY:424,425:"Too Early","4...
         ╵                           ~~~~~~~~~~~~~~~~~


⎔ Starting local server...
[mf:dbg] Updated `Request.cf` object cache!
[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-09-22",
but you've requested "2023-09-27". Falling back to "2023-09-22"...
workerd/server/server.c++:2622: info: Inspector is listening
[mf:inf] Ready on http://0.0.0.0:8787 
[mf:inf] - http://127.0.0.1:8787
[mf:inf] - http://192.168.1.158:8787
workerd/server/server.c++:1099: info: Inspector client attaching [core:user:worker]
